# Generated by Django 5.2.8 on 2025-12-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_cart_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
